import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./context/SessionProvider";
import { NextRequest } from "next/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  request
}: Readonly<{
  children: React.ReactNode;
  request: NextRequest;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`inter.className`} suppressHydrationWarning={true}>
        <SessionProvider>
          <div className="m-auto text-center bg-white flex flex-col min-h-screen">
            <div>
              {/* <Navbar /> */}
            </div>
            <div className="grow">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
